# Generated by Django 2.1.2 on 2018-11-01 09:05

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('company_contract_info', models.CharField(max_length=50)),
                ('company_profile', models.CharField(max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'db_table': 'User',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('amenity_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'amenities',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('seller', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('society', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50)),
                ('longiture', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='NearBy',
            fields=[
                ('nearby_Id', models.AutoField(primary_key=True, serialize=False)),
                ('landmark', models.CharField(max_length=50)),
                ('hospital', models.CharField(max_length=50)),
                ('railway', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'near_by',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('budget', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('bedrooms', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('bathrooms', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('furnished', models.CharField(max_length=50)),
                ('contact_person', models.CharField(max_length=50)),
                ('no_of_carparking', models.CharField(max_length=50)),
                ('posted_by', models.CharField(max_length=50)),
                ('no_of_floors', models.CharField(max_length=50)),
                ('property_type', models.CharField(max_length=50)),
                ('builtup_area', models.CharField(max_length=50)),
                ('land_area', models.CharField(max_length=50)),
                ('carpet_area', models.CharField(max_length=50)),
                ('is_buyable', models.BooleanField(default=False)),
                ('amenity', models.ManyToManyField(related_name='amenities', to='pms.Amenities')),
                ('document', models.ManyToManyField(related_name='document', to='pms.Document')),
                ('location', models.ManyToManyField(related_name='location', to='pms.Location')),
                ('nearby', models.ManyToManyField(related_name='near_by', to='pms.NearBy')),
            ],
            options={
                'db_table': 'property',
            },
        ),
        migrations.CreateModel(
            name='PropertyInterest',
            fields=[
                ('property_interest_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'property_interest',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('property_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'property_type',
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'transaction_type',
            },
        ),
        migrations.CreateModel(
            name='UnitArea',
            fields=[
                ('unit_area_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'unit_area',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('user_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user_type',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='transaction_type',
            field=models.ManyToManyField(related_name='transaction_type', to='pms.TransactionType'),
        ),
        migrations.AddField(
            model_name='property',
            name='unit_area',
            field=models.ManyToManyField(related_name='unit_area', to='pms.UnitArea'),
        ),
        migrations.AddField(
            model_name='property',
            name='user_type',
            field=models.ManyToManyField(related_name='Property_user_type', to='pms.UserType'),
        ),
        migrations.AddField(
            model_name='booking',
            name='property',
            field=models.ManyToManyField(related_name='property', to='pms.Property'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.ManyToManyField(related_name='interest', to='pms.PropertyInterest'),
        ),
        migrations.AddField(
            model_name='user',
            name='property_type',
            field=models.ManyToManyField(related_name='property_type', to='pms.PropertyType'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.ManyToManyField(related_name='user_type', to='pms.UserType'),
        ),
    ]
